spring:
  datasource:
    url: jdbc:mysql://localhost:3306/turn_bd?useSSL=false&serverTimezone=UTC
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 4MB  # Ajusta el tama침o m치ximo permitido para un archivo individual, por ejemplo, 10 MB
      max-request-size: 4MB  # Ajusta el tama침o m치ximo total permitido para la solicitud, por ejemplo, 10 MB

mercado:
  pago:
    access-token: "${APP_MP_TOKEN}"

server:
  url: https://b0ba-2800-810-50c-864-e470-2e8a-1ff3-89c7.ngrok-free.app

# JWT
jwt:
  secret:
    key: "${APP_JWT_TOKEN}"
  time:
    expiration: 86400000
  accessTokenCookieName: AuthToken
