spring:
  datasource:
    url: jdbc:mysql://localhost:3306/turn_db?useSSL=false&serverTimezone=UTC
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
# JWT
jwt:
  secret:
    key: bH0JEkmI05NL/UQyBjER6xkckecLYnLVVg/UbvVumod3E9Nr3SbNxiPMOzFGL+Kd
  time:
    expiration: 86400000
  accessTokenCookieName: AuthToken
